// File generated by Manual Configuration.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8-lonQsZAj6-OPetDYaZ_JGNK9efOFFs',
    appId: '1:887681374750:web:4b6c6a88c634e9e165ec0f',
    messagingSenderId: '887681374750',
    projectId: 'collectio-b6b15',
    authDomain: 'collectio-b6b15.firebaseapp.com',
    storageBucket: 'collectio-b6b15.firebasestorage.app',
    measurementId: 'G-MN6H4SBXVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZkKhpRfaQZLLfN0Sabq3d7zdcZ1dwmOE',
    appId: '1:887681374750:android:c60011d706ac777665ec0f',
    messagingSenderId: '887681374750',
    projectId: 'collectio-b6b15',
    storageBucket: 'collectio-b6b15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2YdAv9J0FwLaLGp_Mr8Li1qpo1K7kXVk',
    appId: '1:887681374750:ios:4ad111185996f45365ec0f',
    messagingSenderId: '887681374750',
    projectId: 'collectio-b6b15',
    storageBucket: 'collectio-b6b15.firebasestorage.app',
    iosBundleId: 'com.example.collectio',
    iosClientId:
        '887681374750-bnhg7frlbr1j0mqhiuj5ehd6p60qbk2b.apps.googleusercontent.com',
  );
}
